### ISSUE TITLE
RuntimeError: Failed to add edge detection

### ISSUE THREAD

**Issue by TheLostProgrammer** [gpiozero/gpiozero#1084]
Operating system: Fedora Server
Python version: Python 3.11.3
Pi model: Pi 4 Model B
GPIO Zero version:  1.6.2
Pin factory used: RPiGPIO

```python
from gpiozero import Button, LED
from signal import pause

led = LED(17)
my_button = Button(2)

def led_on():
    led.on()

my_button.when_pressed = led_on

pause()
```

I ran this code on my Raspberry Pi using:
```
sudo python3 led.py
```

This is the error I receieved:
```
[mypi@rpi ~]$ sudo python3 led.py 
Traceback (most recent call last):
  File "/home/mypi/led.py", line 5, in <module>
    my_button = Button(2)
                ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpiozero/devices.py", line 108, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpiozero/input_devices.py", line 414, in __init__
    super(Button, self).__init__(
  File "/usr/lib/python3.11/site-packages/gpiozero/mixins.py", line 433, in __init__
    super(HoldMixin, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/gpiozero/input_devices.py", line 171, in __init__
    self.pin.when_changed = self._pin_changed
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpiozero/pins/__init__.py", line 432, in <lambda>
    lambda self, value: self._set_when_changed(value),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gpiozero/pins/pi.py", line 319, in _set_when_changed
    self._enable_event_detect()
  File "/usr/lib/python3.11/site-packages/gpiozero/pins/rpigpio.py", line 226, in _enable_event_detect
    GPIO.add_event_detect(
RuntimeError: Failed to add edge detection
```

**Comment by lurch** [comment]
> Operating system: Fedora Server

You might need to try a different pin factory? See https://waldorf.waveform.org.uk/2021/the-pins-they-are-a-changin.html and https://waldorf.waveform.org.uk/2022/the-one-where-dave-breaks-stuff.html for some of the gory details.
