### ISSUE TITLE
Scripts don't work if user doesn't have write permission to CWD

### ISSUE THREAD

**Issue by HiassofT** [gpiozero/gpiozero#1106]
Operating system: RPiOS Bookwork lite 64bit
Python version: 3.11.2
Pi model: Pi 5
GPIO Zero version: 2.0
Pin factory used: default / lgpio

Trying to run a gpiozero script from a directory where the user doesn't have write permissions fails miserably as lgpio tries to create a named pipe in that directory. eg:

```python
from gpiozero import Button

b5 = Button(5)
```
Then run this script eg as user `pi` from the root directory

```
pi@raspberrypi:~ $ cd /
pi@raspberrypi:/ $ python3 ~/gpiotest.py 
2024-01-09 14:52:43 xCreatePipe: Can't set permissions (436) for //.lgd-nfy0, No such file or directory
/usr/lib/python3/dist-packages/gpiozero/devices.py:295: PinFactoryFallback: Falling back from lgpio: [Errno 2] No such file or directory: '.lgd-nfy-3'
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 408, in pin
    pin = self.pins[info]
          ~~~~~~~~~^^^^^^
KeyError: PinInfo(number=29, name='GPIO5', names=frozenset({'GPIO5', 5, 'BOARD29', 'WPI21', '5', 'J8:29', 'BCM5'}), pull='', row=15, col=1, interfaces=frozenset({'', 'dpi', 'spi', 'gpio', 'uart', 'i2c'}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/gpiotest.py", line 3, in <module>
    b5 = Button(5)
         ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 412, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 417, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 162, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 243, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 79, in __init__
    super().__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 549, in __init__
    pin = self.pin_factory.pin(pin)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 410, in pin
    pin = self.pin_class(self, info)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 101, in __init__
    GPIO.setup(self._number, GPIO.IN, self.GPIO_PULL_UPS[self._pull])
RuntimeError: Cannot determine SOC peripheral base address
```

Running the script from a directory where the user has write permission works but after exit the current working directory is cluttered with a name pipe:
```
pi@raspberrypi:/ $ cd ~
pi@raspberrypi:~ $ python3 gpiotest.py 
pi@raspberrypi:~ $ ls -la .lgd*
prw-rw-r-- 1 pi pi 0 Jan  9 15:07 .lgd-nfy0
pi@raspberrypi:~ $ 
```

lgpio seems to have a `lguSetWorkDir` function and a `LG_WD` environment variable to configure the directory where it creates it's pipe(s) and it might be a good idea to set that to something safe like `/tmp/gpiozero-PID/` that's guaranteed to be writable and not clash when running multiple scripts using gpiozero/lgpio in parallel - that seems to be the recommended solution until the underlying lgpio issue https://github.com/joan2937/lg/issues/12 is resolved

**Comment by m666m** [comment]
This file `.lgd-nfy0` exists in the directorys with running `pinout`, everytime everywhere...

**Comment by NicolaP8** [comment]
WOW in 2024 still exists this kind of bug!
I'm suffering the same problem.
Temporary file has to be in the /tmp directory.

**Comment by lurch** [comment]
> This seems to be happening when lgpio is directly used too... So, it is probably not an issue with GPIOZero, which is said to be using lgpio underneath

Yes, see https://github.com/joan2937/lg/issues/12 (which was already mentioned above).

**Comment by txoof** [comment]
@haricane8133 
> This seems to be happening when lgpio is directly used too... So, it is probably not an issue with GPIOZero, which is said to be using lgpio underneath

Do you have any suggestions as to how to work around this? I'm trying to run a program that access gpio from a daemon service and it fails miserably with the xCreatePipe failure seen above. I see from the issue linked above that it's possible to specify a working directory when starting rgpiod:

>The daemon [rgpiod](http://abyz.me.uk/lg/rgpiod.html) has the -w option. The other programs will pick up their working directory from the LG_WD environment variable. E.g. `export LG_WD=/tmp`

But I'm totally at a loss as to how this is done. Any ideas?

**Comment by richardfelton1** [comment]
Thank you @txoof 
I had a similar error. Solved with the "RuntimeDirectory" and "WorkingDirectory" directives in the [Service] section.

```
Sep 21 17:52:58 raspberrypi bash[18202]: My IP address is 192.168.1.215 2a00:23c8:c133:ed01:5a05:544e:c7a3:5403
Sep 21 17:53:00 raspberrypi python3[18203]: 2024-09-21 17:53:00 xCreatePipe: Can't set permissions (436) for //.lgd-nfy0, Operation not perm>
Sep 21 17:53:00 raspberrypi python3[18203]: /usr/lib/python3/dist-packages/gpiozero/devices.py:300: PinFactoryFallback: Falling back from lg>
Sep 21 17:53:00 raspberrypi python3[18203]:   warnings.warn(
Sep 21 17:53:00 raspberrypi python3[18203]: Traceback (most recent call last):
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/home/pi/urace/button_control.py", line 135, in <module>
Sep 21 17:53:00 raspberrypi python3[18203]:     btn = Button(btnGPIO, pull_up=True, hold_time=tBtnPolling, hold_repeat=True)
Sep 21 17:53:00 raspberrypi python3[18203]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 108, in __call__
Sep 21 17:53:00 raspberrypi python3[18203]:     self = super().__call__(*args, **kwargs)
Sep 21 17:53:00 raspberrypi python3[18203]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 412, in __init__
Sep 21 17:53:00 raspberrypi python3[18203]:     super().__init__(
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 417, in __init__
Sep 21 17:53:00 raspberrypi python3[18203]:     super().__init__(*args, **kwargs)
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 168, in __init__
Sep 21 17:53:00 raspberrypi python3[18203]:     self.pin.when_changed = self._pin_changed
Sep 21 17:53:00 raspberrypi python3[18203]:     ^^^^^^^^^^^^^^^^^^^^^
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/usr/lib/python3/dist-packages/gpiozero/pins/__init__.py", line 471, in <lambda>
Sep 21 17:53:00 raspberrypi python3[18203]:     lambda self, value: self._set_when_changed(value),
Sep 21 17:53:00 raspberrypi python3[18203]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 639, in _set_when_changed
Sep 21 17:53:00 raspberrypi python3[18203]:     self._enable_event_detect()
Sep 21 17:53:00 raspberrypi python3[18203]:   File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 220, in _enable_event_det>
Sep 21 17:53:00 raspberrypi python3[18203]:     GPIO.add_event_detect(
Sep 21 17:53:00 raspberrypi python3[18203]: RuntimeError: Failed to add edge detection
Sep 21 17:53:01 raspberrypi systemd[1]: urace-startup.service: Main process exited, code=exited, status=1/FAILURE
```
