### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by nikhiljohn10** [gpiozero/gpiozero#886]
Operating system: Raspberry Pi OS Lite 32bit
Python version: 3.7.3
Pi model: Pi 4 Model B
GPIO Zero version: 1.5.1
Pin factory used: RPiGPIO
[pi-clap](https://github.com/nikhiljohn10/pi-clap) used: 1.3.1

The behavior observed when the connection is closed while the LED is blinking and not completed the counts of blinks. Is there a way to break the count in middle and safely close the program if main thread stops?

```
Exception ignored in: <function GPIOBase.__del__ at 0xb5b611e0>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/gpiozero/devices.py", line 151, in __del__
    self.close()
  File "/home/pi/.local/lib/python3.7/site-packages/gpiozero/output_devices.py", line 224, in close
    self._stop_blink()
  File "/home/pi/.local/lib/python3.7/site-packages/gpiozero/output_devices.py", line 269, in _stop_blink
    self._blink_thread.stop()
  File "/home/pi/.local/lib/python3.7/site-packages/gpiozero/threads.py", line 72, in stop
    self.join(timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/gpiozero/threads.py", line 75, in join
    super(GPIOThread, self).join(timeout)
  File "/usr/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```
```python
#!/usr/bin/python3

import os
from piclap import *
from gpiozero import LED


class PiController:
    '''Describes the controller methods which are usually used while connected
    to a raspberry pi controller using the module `gpiozero`.
    '''

    def __init__(self):
        self.led12 = LED(12)
        self.led24 = LED(24)

    def toggleLight(self):
        self.led12.toggle()
        print("Light toggled on pin 12")

    def lightBlinker(self, times=10):
        self.led24.blink(n=times)
        print("Light blinks", times, "times on pin 24")


class Config(Settings):
    '''Describes custom configurations and action methods to be executed based
    on the number of claps detected.
    '''

    def __init__(self):
        super().__init__()
        self.controller = PiController()
        self.chunk_size = 512       # Reduce as power of 2 if pyaudio overflow
        self.interval = 0.5         # Adjust interval between claps
        self.method.value = 600   # Threshold value adjustment

    def on2Claps(self):
        '''Custom action for 2 claps'''
        self.controller.led12.blink(n=1)
        print("Light flashed on pin 4")

    def on3Claps(self):
        '''Custom action from PiController for 3 claps'''
        self.controller.toggleLight()

    def on5Claps(self):
        '''Custom action from PiController for 5 claps'''
        self.controller.lightBlinker(times=5)


def main():
    config = Config()
    listener = Listener(config)
    os.system('clear')
    listener.start()


if __name__ == '__main__':
    main()
```

**Comment by bennuttall** [comment]
Sorry I didn't see this at the time. If you are still having issues please reply and we'll reopen the issue.

What is `Listener`?

Have you tried without `os.system`? I seem to remember that causing issues in the past.
