### ISSUE TITLE
ZombieThread

### ISSUE THREAD

**Issue by Dieter-D** [gpiozero/gpiozero#887]
Hello I am using v1.5.1 of the gpiozero package.

The first time after boot up I try to close my python application the gpiozero package fails to shutdown in a clean way. I always get a 
```
"gpiozero.exc.ZombieThread: Thread failed to die within 10 seconds" 
```
message and a traceback like the one below.

Is there a way to avoid this error?

During the shutdown procedure of my program I am using the "close()" function for each Device (LED, Button) I am using.
Do I have to call additional functions/methods to get a clean shutdown?

Thanks in advance.

PS : I am running the application on a Raspi Zero with Rasbian / Debian Buster from May 2020 (Raspberry Pi OS lite)

Here is the traceback:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 594, in _shutdown
    _threads_shutdown()
  File "/usr/lib/python3/dist-packages/gpiozero/threads.py", line 54, in _threads_shutdown
    t.join(10)
  File "/usr/lib/python3/dist-packages/gpiozero/threads.py", line 81, in join
    "Thread failed to die within %d seconds" % timeout)
gpiozero.exc.ZombieThread: Thread failed to die within 10 seconds
Exception ignored in: <function GPIOBase.__del__ at 0xb6057150>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 151, in __del__
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 392, in close
  File "/usr/lib/python3/dist-packages/gpiozero/threads.py", line 72, in stop
  File "/usr/lib/python3/dist-packages/gpiozero/threads.py", line 81, in join
gpiozero.exc.ZombieThread: Thread failed to die within 10 seconds
Exception ignored in: <function GPIOBase.__del__ at 0xb6057150>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 151, in __del__
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 392, in close
  File "/usr/lib/python3/dist-packages/gpiozero/threads.py", line 72, in stop
  File "/usr/lib/python3/dist-packages/gpiozero/threads.py", line 81, in join
gpiozero.exc.ZombieThread: Thread failed to die within 10 seconds
```

**Comment by bennuttall** [comment]
Sorry I didn't see this at the time. If you still have this issue please reply with some code to reproduce and we'll reopen the issue.
