### ISSUE TITLE
AttributeError in mixins.py _fire_activated() because self._hold_thread.holding is None

### ISSUE THREAD

**Issue by ddan39** [gpiozero/gpiozero#956]
Operating system: Raspbian 10.9
Python version: 3.7.3
Pi model: Pi 4 Model B
GPIO Zero version: 1.5.1
Pin factory used: pigio

This looks like a race condition with the Button class's logic for when/is_held. After instantiating a new Button object my program crashes with the follow traceback:

    Traceback (most recent call last):
        File "/home/pi/myTest.py", line 250, in <module>
            resetBut = Button(reset_pin, bounce_time=0.020)
        File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 124, in __call__
            self = super(GPIOMeta, cls).__call__(*args, **kwargs)
        File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 432, in __init__
            bounce_time=bounce_time, pin_factory=pin_factory)
        File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 383, in __init__
            super(HoldMixin, self).__init__(*args, **kwargs)
        File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 188, in __init__
            self._fire_events(self.pin_factory.ticks(), self.is_active)
        File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 368, in _fire_events
            self._fire_activated()
        File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 398, in fire_activated
            self._hold_thread.holding.set()
    AttributeError: 'NoneType' object has no attribute 'holding'

**Comment by waveform80** [comment]
I think I see the issue here. You must have an edge coming in precisely during construction of the `Button`. The initial call to `_fire_events` in `InputDevices.__init__` *assumes* that it's the first such call, but the `pin.when_changed` handler has already been set up in the line before and so an edge at that time could race it, and `_fire_events` becomes the *second* such call which'll then expect everything else (like the `_hold_thread` which hasn't been created yet) to be set up.
